'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.1
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("CG.FairShare.Data.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;windows-1252&quot;?&gt;
        '''&lt;request&gt;
        '''	&lt;command&gt;editrule&lt;/command&gt;
        '''	&lt;rulename&gt;limme&lt;/rulename&gt;
        '''	&lt;ruleset&gt;
        '''		&lt;rule name=&quot;limme&quot; active=&quot;1&quot; direction=&quot;0&quot; protocol=&quot;3&quot; interface=&quot;0&quot; rate-type=&quot;0&quot; rate-id=&quot;0&quot; rate=&quot;?RATE&quot; rate2=&quot;0&quot; combined=&quot;0&quot; penality=&quot;0&quot; timetable-id=&quot;0&quot; mapping-id=&quot;0&quot;&gt;
        '''			&lt;mapping-filter type=&quot;0&quot; count=&quot;0&quot;/&gt;
        '''			&lt;date-bound&gt;
        '''				&lt;active&gt;always&lt;/active&gt;
        '''				&lt;date&gt;40891&lt;/date&gt;
        '''			&lt;/date-bound&gt;
        '''			&lt;stats&gt;
        '''				&lt;total since=&quot;1899-12-30T00-00-00&quot; traffic-in-lo=&quot;0&quot; tra [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property setrule() As String
            Get
                Return ResourceManager.GetString("setrule", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
